qtable/qtable/urls.py
"""
This module defines the URL patterns for routing within the Django application, including admin, app-specific views,
user-related views, and email verification.

URL Patterns:
    - 'admin/': Maps to the Django admin site for administrative tasks and management.
    - '': Includes URL patterns from the 'qtable_app' application for handling specific app-related views.
    - 'users/': Includes URL patterns from the 'users' application for managing user-related views such as registration,
        login, and logout.
    - 'email/': Includes URL patterns for email verification using the django_email_verification package.

Usage:
    The URL configuration ensures proper routing within the Django application, allowing users to access various
    functionalities such as administrative tasks, app-specific views, user management, and email verification.
    Each URL pattern is associated with a specific application or functionality, ensuring a structured and organized
    routing system for the application.

Note:
    The use of the 'include' function allows for modular URL configuration by including URL patterns from other Django
    applications or packages, facilitating maintainability and scalability.
"""
from django.contrib import admin
from django.urls import include, path
from django_email_verification import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('qtable_app.urls')),
    path('users/', include('users.urls')),
    path('email/', include(urls)),
]

qtable/qtable_app/urls.py
"""
This module defines URL patterns related to the 'qtable_app' within the Django application.

URL Patterns:
    - '': Maps to the IndexView class, serving as the main landing page of the application.
    - 'quotes/<int:page>/': Maps to the QuotesListView class, displaying a paginated list of quotes from the external
        API.
    - 'favorites/': Maps to the FavoritesListView class, displaying a list of favorite quotes for the authenticated
        user.
    - '<int:pk>/': Maps to the FavoriteSetView class, allowing users to toggle the favorite status for a specific quote
        of the day.

Views:
    - IndexView: Represents the main landing page of the application, displaying the quote of the day.
    - QuotesListView: Displays a paginated list of quotes fetched from an external API.
    - FavoritesListView: Displays a list of favorite quotes for the authenticated user.
    - FavoriteSetView: Allows users to add or remove a specific quote from their favorites.

Usage:
    The URL configuration ensures that users can navigate to appropriate endpoints within the 'qtable_app', including
    viewing quotes, managing favorites, and toggling favorite statuses.
    Each URL pattern is associated with a specific view class, providing functionality tailored to the user's
    interaction with the application.

Note:
    The 'app_name' variable is set to 'qtable_app', ensuring that the URL patterns are namespaced under the 'qtable_app'
    application.
"""

from django.urls import path

from .views import FavoriteSetView, FavoritesListView, IndexView, QuotesListView

app_name = 'qtable_app'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('quotes/<int:page>/', QuotesListView.as_view(), name='quotes'),
    path('favorites/', FavoritesListView.as_view(), name='favorites'),
    path('<int:pk>/', FavoriteSetView.as_view(), name='add_favorite'),
]

qtable/users/urls.py
"""
This module defines URL patterns related to user authentication and registration within the application.

URL Patterns:
    - 'signup/': Maps to the RegisterView class to handle user registration.
    - 'login/': Maps to the LoginView class for user authentication. It uses a custom template and form for login,
        and handles redirecting authenticated users to the appropriate page.
    - 'logout/': Maps to the LogoutView class to handle user logout functionality.
    - 'confirm_email/<int:pk>/': Maps to the confirm_email view function to confirm a user's email address,
        using a specific primary key.

Views and Forms:
    - RegisterView: Handles user registration, allowing new users to create accounts.
    - LoginView: Manages user authentication, providing a custom login template and form.
    - LogoutView: Implements user logout functionality to end user sessions.
    - confirm_email: A view function that confirms a user's email address by accepting a primary key as an argument.

Usage:
    The URL configuration ensures that users can navigate to appropriate endpoints for user registration, login, logout,
    and email confirmation.
    The provided views and forms manage user authentication processes, allowing users to interact securely with the
    application.
    The 'extra_context' parameter in the LoginView is utilized to provide additional context data, such as the title for
    the login page.

Note:
    The 'app_name' variable is set to 'users', ensuring that the URL patterns are namespaced under the 'users'
    application.
"""
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import RegisterView, confirm_email

app_name = 'users'

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='signup'),
    path(
        'login/',
        LoginView.as_view(
            template_name='users/login.html',
            authentication_form=AuthenticationForm,
            redirect_authenticated_user=True,
            extra_context={'title': 'Login'},
        ), name='login',
    ),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('confirm_email/<int:pk>/', confirm_email, name='confirm_email'),
]

qtable/qtable_app/models.py
"""
This module defines the QuoteOfDay model and its associated fields for storing daily quotes within the application.

Model:
    - QuoteOfDay: Represents a daily quote with fields for quote content, author, creation date, last updated date,
        and user favorites.

Fields and Relationships:
    - quote: Represents the content of the daily quote.
    - author: Represents the author of the daily quote.
    - date: Represents the creation date of the daily quote.
    - updated: Represents the last updated date of the daily quote.
    - users: Establishes a many-to-many relationship with the built-in User model, allowing users to mark quotes as
        favorites.

Usage:
    The module provides the QuoteOfDay model for storing daily quotes and facilitating user interactions such as marking
    quotes as favorites.
    Developers can utilize this model to manage daily quotes and associated user favorites within the application.

Note:
    The module focuses on defining the QuoteOfDay model and its associated fields, enabling the application to manage
    daily quotes and user preferences effectively.
"""
from django.contrib.auth.models import User
from django.db.models import CharField, DateTimeField, ManyToManyField, Model, TextField


class QuoteOfDay(Model):
    """Represents a daily quote with fields for quote content, author, creation date, last updated date."""

    quote = TextField()
    author = CharField(max_length=100)
    date = DateTimeField(auto_now_add=True)
    updated = DateTimeField(auto_now=True)
    users = ManyToManyField(User, 'favorites')

qtable/qtable_app/views.py
"""
This module contains Django views related to handling quotes from an external API and managing user favorites.

Classes:
    - BaseQuoteView: A base view class to fetch quotes from a specified URL.
    - IndexView: A view class to display the quote of the day.
    - QuotesListView: A view class to display a list of quotes from the external API.
    - FavoritesListView: A view class to display a list of favorite quotes for the authenticated user.
    - FavoriteSetView: A view class to toggle the favorite status for a specific quote of the day.

Attributes:
    - url: The URL from which quotes are fetched, specified in each respective view class.

Methods:
    - get_response(): Fetches a response from the specified URL, optionally paginating through results.
    - IndexView.get(): Renders the template for the quote of the day, fetching it from an API if not available.
    - QuotesListView.get(): Renders a template displaying a list of quotes from an external API.
    - FavoritesListView.get_queryset(): Returns a queryset of favorite quotes for the authenticated user.
    - FavoritesListView.get_context_data(): Provides context data for rendering the favorites list view.
    - FavoriteSetView.get(): Toggles the favorite status of a specific quote for the authenticated user.

Usage:
    This module provides the necessary views to display quotes, manage user favorites, and toggle favorite status.
    It integrates with an external API ('https://api.quotable.io/') to fetch quotes and allows users to mark quotes as
    favorites.
    The views are designed to handle user authentication, providing a personalized experience based on user preferences.

Note:
    The 'LoginRequiredMixin' is used to ensure that only authenticated users can access certain views, such as managing
    favorites.
"""

from datetime import date

import httpx
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import QuerySet
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.generic import ListView, View

from .models import QuoteOfDay


class BaseQuoteView(View):
    """A base view class for retrieving quotes from a given URL."""

    url = None

    def get_response(self, page: int = None) -> dict | list:
        """
        Retrieve a response from the given URL.

        :param page: The page number to retrieve. Defaults to None.
        :type page: int, optional

        :return: The JSON response from the URL.
        :rtype: dict | list
        """
        if page:
            self.url = f'{self.url}?page={page}'
        response = httpx.get(self.url)
        return response.json()


class IndexView(BaseQuoteView):
    """A view class for displaying the quote of the day."""

    template_name = 'qtable_app/index.html'
    url = 'https://api.quotable.io/quotes/random'

    def get(self, request: HttpRequest, page: int = None) -> HttpResponse:
        """
        Retrieve the quote of the day and renders it along with additional context data.

        :param request: The HTTP request object.
        :type request: HttpRequest
        :param page: The page number.
        :type page: int, optional
        :return: The HTTP response containing the rendered template.
        :rtype: HttpResponse
        """
        quote_of_day = QuoteOfDay.objects.filter(date__date=date.today()).first()
        if not quote_of_day:
            response = self.get_response()[0]
            quote_of_day = QuoteOfDay(quote=response.get('content'), author=response.get('author'))
            quote_of_day.save()
        context = {
            'title': 'Quote of the Day',
            'quote': quote_of_day,
            'favorites': request.user.favorites.all() if request.user.is_authenticated else None,
        }
        return render(request, self.template_name, context)


class QuotesListView(BaseQuoteView):
    """A view class for displaying a list of quotes."""

    template_name = 'qtable_app/quotes_list.html'
    url = 'https://api.quotable.io/quotes'

    def get(self, request: HttpRequest, page: int = None) -> HttpResponse:
        """
        Render a template displaying a list of quotes from an external API.

        :param request: The HTTP request object.
        :type request: HttpRequest
        :param page: The page number to retrieve. Defaults to None.
        :type page: int, optional
        :return: The HTTP response object containing the rendered template.
        :rtype: HttpResponse
        """
        context = {
            'title': 'Quotes List',
            'quotes': self.get_response(page),
            'favorites': request.user.favorites.all() if request.user.is_authenticated else None,
        }
        return render(request, self.template_name, context)


class FavoritesListView(LoginRequiredMixin, ListView):
    """View for displaying a list of favorite users for the current user."""

    template_name = 'qtable_app/favorites.html'
    url = 'https://api.quotable.io/quotes'
    paginate_by = 4

    def get_queryset(self) -> QuerySet:
        """
        Return the queryset of favorite users for the current user.

        :param self: The current instance of the class.
        :return: A queryset of User objects representing the favorite users of the current user.
        :rtype: QuerySet[User]
        """
        return self.request.user.favorites.all()

    def get_context_data(self, **kwargs) -> dict:
        """
        Retrieve and returns the context data for the view.

        :param kwargs: Additional keyword arguments.
        :type kwargs: dict

        :return: A dictionary containing the context data for the view.
        :rtype: dict
        """
        context = super().get_context_data(**kwargs)
        context['title'] = 'Favorites'
        context['favorites'] = self.request.user.favorites.all()
        return context


class FavoriteSetView(LoginRequiredMixin, View):
    """View for toggling favorite status for a specific quote of the day."""

    def get(self, request: HttpRequest, pk: int) -> HttpResponseRedirect:
        """
        Retrieve a specific quote of the day and toggles its favorite status for the authenticated user.

        :param request: The HTTP request object.
        :type request: HttpRequest
        :param pk: The primary key of the quote of the day to retrieve.
        :type pk: int
        :return: A redirect response to the next URL specified in the request's GET parameters.
        :rtype: HttpResponseRedirect
        """
        user = get_object_or_404(User, pk=request.user.pk)
        favorite = get_object_or_404(QuoteOfDay, pk=pk)
        if favorite in user.favorites.all():
            user.favorites.remove(favorite)
        else:
            user.favorites.add(favorite)
        user.save()
        next_url = request.GET.get('next', reverse('qtable_app:index'))
        return redirect(next_url)

qtable/qtable_app/templates/qtable_app/base.html
<!doctype html>
<html lang="en" data-bs-theme="light">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% load static %}
    <link href="{% static 'main.css'%}" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
            crossorigin="anonymous"></script>
    <title>{{ title }}</title>
</head>
<body class="d-flex text-center text-bg-dark">
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class="mb-auto">
        <div>
            <h3 class="float-md-start mb-0">QTable</h3>
            <nav class="nav nav-masthead justify-content-center float-md-end">
                <a class="nav-link fw-bold py-1 px-0{% if request.path|length <= 3 %} active{% endif %}"
                   aria-current="page" href="{% url 'qtable_app:index' %}">
                    Home
                </a>
                <a class="nav-link fw-bold py-1 px-0{% if 'quotes' in request.path %} active{% endif %}"
                   href="{% url 'qtable_app:quotes' 1 %}">List</a>
                {% if user.is_authenticated %}
                <a class="nav-link fw-bold py-1 px-0{% if 'favorites' in request.path %} active{% endif %}"
                   href="{% url 'qtable_app:favorites' %}">Favorites</a>
                <form class="ms-3" action="{% url 'users:logout' %}" method="post">
                    {% csrf_token %}
                    <button class="nav-link fw-bold py-1 px-0{% if 'logout' in request.path %} active{% endif %}"
                            type="submit">Log out</button>
                </form>
                {% else %}
                <a class="nav-link fw-bold py-1 px-0{% if 'signup' in request.path %} active{% endif %}"
                   href="{% url 'users:signup' %}">Sign up</a>
                <a class="nav-link fw-bold py-1 px-0{% if 'login' in request.path %} active{% endif %}"
                   href="{% url 'users:login' %}">Login</a>
                {% endif %}
            </nav>
        </div>
    </header>
    <main class="px-3">
        {% block content %}{% endblock %}
    </main>
    <footer class="mt-auto pt-5 text-white-50">
        <p>Made by <a href="https://github.com/GodVov4/" class="text-white">GodVov4</a>.</p>
    </footer>
</div>
</body>
</html>

qtable/qtable_app/templates/qtable_app/favorites.html
{% extends "qtable_app/base.html" %}

{% block content %}

<div class="container d-flex justify-content-center align-items-center" style="height: 83vh;">
    <div>
        <h2>Favorites</h2>
        {% for quote in object_list %}
        <p class="m-0, mt-5">
            <a class="link-underline link-underline-opacity-0 mx-1"
               href="{% url 'qtable_app:add_favorite' quote.id %}?next={{ request.path }}?page={{ request.GET.page }}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="white" class="bi bi-star"
                     viewBox="0 0 16 16">
                    {% if quote in favorites %}
                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                    {% else %}
                    <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.56.56 0 0 0-.163-.505L1.71 6.745l4.052-.576a.53.53 0 0 0 .393-.288L8 2.223l1.847 3.658a.53.53 0 0 0 .393.288l4.052.575-2.906 2.77a.56.56 0 0 0-.163.506l.694 3.957-3.686-1.894a.5.5 0 0 0-.461 0z"/>
                    {% endif %}
                </svg>
            </a>
            {{ quote.quote }}
        </p>
        <small>Author: {{ quote.author }}</small>
        {% endfor %}
        {% if page_obj.has_other_pages %}
        <nav class="pt-5" aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li class="page-item">
                    <a class="page-link{% if not page_obj.has_previous %} disabled{% else %} text-primary text-opacity-75{% endif %}"
                       {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}" {% endif %}>
                        Previous
                    </a>
                </li>
                <li class="page-item">
                    <a class="page-link{% if not page_obj.has_next %} disabled{% else %} text-primary text-opacity-75{% endif %}"
                       {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}" {% endif %}>
                        Next
                    </a>
                </li>
            </ul>
        </nav>
        {% endif %}
    </div>
</div>

{% endblock %}

qtable/qtable_app/templates/qtable_app/index.html
{% extends "qtable_app/base.html" %}

{% block content %}

<div class="container d-flex justify-content-center align-items-center" style="height: 83vh;">
    <div>
        <h2>Quote of the Day</h2>
        <p class="pt-5">{{ quote.quote }}</p>
        <small>Author: {{ quote.author }}</small>
    </div>
</div>

{% endblock %}

qtable/qtable_app/templates/qtable_app/quotes_list.html
{% extends "qtable_app/base.html" %}

{% block content %}

<h2>Quotes List</h2>
{% for quote in quotes.results %}
<p class="m-0, mt-5">
    {% if quote in favorites %}
    <a class="link-underline link-underline-opacity-0" href="#">
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="white" class="bi bi-star"
             viewBox="0 0 16 16">
            {% if quote in favorites %}
            <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
            {% else %}
            <path d="M2.866 14.85c-.078.444.36.791.746.593l4.39-2.256 4.389 2.256c.386.198.824-.149.746-.592l-.83-4.73 3.522-3.356c.33-.314.16-.888-.282-.95l-4.898-.696L8.465.792a.513.513 0 0 0-.927 0L5.354 5.12l-4.898.696c-.441.062-.612.636-.283.95l3.523 3.356-.83 4.73zm4.905-2.767-3.686 1.894.694-3.957a.56.56 0 0 0-.163-.505L1.71 6.745l4.052-.576a.53.53 0 0 0 .393-.288L8 2.223l1.847 3.658a.53.53 0 0 0 .393.288l4.052.575-2.906 2.77a.56.56 0 0 0-.163.506l.694 3.957-3.686-1.894a.5.5 0 0 0-.461 0z"/>
            {% endif %}
        </svg>
    </a>
    {% endif %}
    {{ quote.content }}
</p>
<small>Author: {{ quote.author }}</small>
{% endfor %}
<nav class="pt-5" aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        <li class="page-item">
            <a class="page-link{% if quotes.page == 1 %} disabled{% else %} text-primary text-opacity-75{% endif %}"
               {% if quotes.page != 1 %}href="{% url 'qtable_app:quotes' quotes.page|add:'-1' %}" {% endif %}>
                Previous
            </a>
        </li>
        <li class="page-item">
            <a class="page-link{% if quotes.page == quotes.totalPages %} disabled{% else %} text-primary text-opacity-75{% endif %}"
               {% if quotes.page != quotes.totalPages %}href="{% url 'qtable_app:quotes' quotes.page|add:'1' %}" {% endif %}>
                Next
            </a>
        </li>
    </ul>
</nav>

{% endblock %}